# インストールに時間がかかるため、優先度の高いものからインストール
cask "google-chrome"
cask "visual-studio-code"
cask "cursor"
cask "google-japanese-ime"
brew "mise"
cask "docker"
cask "raycast"
cask "ghostty"
cask "karabiner-elements"
cask "notion"
cask "zoom"

# 開発ツールやユーティリティ
brew "curl"
brew "direnv"

# プログラミング言語
brew "typst"
brew "perl"
brew "protobuf"
brew "zig"

# バージョン管理
brew "git-lfs"
brew "gh"

# サーバー・データベース
brew "mysql"
brew "postgresql@17", restart_service: true, link: true
brew "sqlite"
brew "openssh"

# その他
brew "ios-deploy" # iOSデバイスにアプリをデプロイするツール
brew "k6" # 負荷テストツール
brew "mas" # Mac App Storeのアプリをコマンドラインからインストールするツール

# アプリケーション
cask "discord"
cask "slack"
cask "spotify"
cask "firefox"
cask "microsoft-edge"
cask "arc"
cask "mattermost"
cask "obs"
cask "dbeaver-community"
cask "wireshark"
cask "utm"
cask "microsoft-office"
cask "microsoft-remote-desktop"
cask "mactex" # LaTeX環境。インストールに時間がかかる

# フォント
cask "font-plemol-jp" # Plemol JP フォント
cask "font-plemol-jp-hs" # Plemol JP ハーフスリムフォント
cask "font-plemol-jp-nf" # Plemol JP Nerd フォント
cask "font-monaspace" # https://github.com/githubnext/monaspace
